/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nukkitx_natives_sha256_NativeSha256 */

#ifndef _Included_com_nukkitx_natives_sha256_NativeSha256
#define _Included_com_nukkitx_natives_sha256_NativeSha256
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nukkitx_natives_sha256_NativeSha256
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nukkitx_natives_sha256_NativeSha256_init
  (JNIEnv *, jobject);

/*
 * Class:     com_nukkitx_natives_sha256_NativeSha256
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_sha256_NativeSha256_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nukkitx_natives_sha256_NativeSha256
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_sha256_NativeSha256_reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nukkitx_natives_sha256_NativeSha256
 * Method:    update
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_sha256_NativeSha256_update__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_nukkitx_natives_sha256_NativeSha256
 * Method:    update
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_sha256_NativeSha256_update__J_3BII
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_nukkitx_natives_sha256_NativeSha256
 * Method:    digest
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nukkitx_natives_sha256_NativeSha256_digest
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
