/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nukkitx_natives_aes_NativeAes */

#ifndef _Included_com_nukkitx_natives_aes_NativeAes
#define _Included_com_nukkitx_natives_aes_NativeAes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nukkitx_natives_aes_NativeAes
 * Method:    init
 * Signature: (Z[B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_nukkitx_natives_aes_NativeAes_init
  (JNIEnv *, jclass, jboolean, jbyteArray, jbyteArray);

/*
 * Class:     com_nukkitx_natives_aes_NativeAes
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_aes_NativeAes_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nukkitx_natives_aes_NativeAes
 * Method:    cipherBytesToBytes
 * Signature: (J[BI[BII)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_aes_NativeAes_cipherBytesToBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_nukkitx_natives_aes_NativeAes
 * Method:    cipherBytesToBuffer
 * Signature: (J[BIJI)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_aes_NativeAes_cipherBytesToBuffer
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jlong, jint);

/*
 * Class:     com_nukkitx_natives_aes_NativeAes
 * Method:    cipherBufferToBytes
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_aes_NativeAes_cipherBufferToBytes
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_nukkitx_natives_aes_NativeAes
 * Method:    cipherBufferToBuffer
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_com_nukkitx_natives_aes_NativeAes_cipherBufferToBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
