/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor */

#ifndef _Included_org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor
#define _Included_org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor
 * Method:    init
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor_init
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor
 * Method:    deflate
 * Signature: (JJIJII)I
 */
JNIEXPORT jint JNICALL Java_org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor_deflate
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jint);

/*
 * Class:     org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor
 * Method:    inflate
 * Signature: (JJIJI)I
 */
JNIEXPORT jint JNICALL Java_org_cloudburstmc_natives_zlib_LibdeflateZlibProcessor_inflate
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
